package com.designtocode.cli

import com.designtocode.config.PipelineConfig
import com.designtocode.domain.ContextBuilder
import com.designtocode.domain.CoverageType
import com.designtocode.domain.PromptConstructor
import com.designtocode.domain.QualityGateValidator
import com.designtocode.domain.adapter.GitHubCliAdapter
import com.designtocode.domain.adapter.OllamaAdapter
import com.designtocode.domain.port.GitOperationsPort
import java.io.File
import kotlinx.coroutines.runBlocking

class PipelineOrchestrator(
    private val workspacePath: String,
    private val changedFiles: List<String>,
    private val ollamaModel: String,
    private val config: PipelineConfig
) {

    fun execute(): PipelineResult = runBlocking {
        println("=== Design-to-Code AI Pipeline ===")
        
        // Stage 1: Context Analysis
        println("[Stage 1] Context Analysis & Detection")
        val buildFile = File(workspacePath, "build.gradle.kts")
        val contextBuilder = ContextBuilder(buildFile)
        val projectContext = contextBuilder.buildContext()
        println("Detected: ${projectContext.techStack.toFriendlyName()}, ${projectContext.database.toFriendlyName()}")
        
        // Stage 2: Prompt Construction
        println("[Stage 2] Prompt Construction")
        val rulesDir = File(workspacePath, "rules")
        val promptConstructor = PromptConstructor(rulesDir)
        val prompt = promptConstructor.constructPrompt(projectContext, changedFiles)
        println("Prompt constructed with ${changedFiles.size} spec files")
        
        // Stage 3: AI Generation
        println("[Stage 3] AI Generation")
        val ollamaAdapter = OllamaAdapter(
            host = config.ai.host,
            port = config.ai.port,
            model = ollamaModel,
            timeoutMs = config.ai.timeoutMs
        )
        val aiResult = ollamaAdapter.generate(prompt, File(workspacePath))
        if (!aiResult.success) {
            println("AI generation failed: ${aiResult.errorMessage}")
            return@runBlocking PipelineResult(success = false, errorMessage = aiResult.errorMessage)
        }
        println("AI generation completed")
        
        // Stage 4: Quality Gate Validation
        println("[Stage 4] Quality Gate Validation")
        val coverageType = when (config.qualityGate.coverageType.uppercase()) {
            "BRANCH" -> CoverageType.BRANCH
            "INSTRUCTION" -> CoverageType.INSTRUCTION
            else -> CoverageType.LINE
        }
        val qualityValidator = QualityGateValidator(
            projectDir = File(workspacePath),
            coverageThreshold = config.qualityGate.coverageThreshold,
            timeoutSeconds = config.qualityGate.timeoutSeconds,
            coverageType = coverageType
        )
        val qualityResult = qualityValidator.validate()
        if (!qualityResult.passed) {
            println("Quality gate failed: ${qualityResult.errorMessage}")
            return@runBlocking PipelineResult(success = false, errorMessage = qualityResult.errorMessage)
        }
        println("Quality gate passed: ${qualityResult.coveragePercentage}% coverage")
        
        // Stage 5: Git Operations
        println("[Stage 5] Git Operations & PR Creation")
        val gitOperations: GitOperationsPort = GitHubCliAdapter(File(workspacePath))
        val branchName = "${config.git.branchPrefix}-${System.currentTimeMillis()}"
        gitOperations.createFeatureBranch(branchName)
        gitOperations.commitChanges("feat: AI-generated code changes")
        val prResult = gitOperations.createPullRequest(
            title = "AI-generated code changes",
            description = "Generated by Design-to-Code AI Pipeline",
            qualityResult = qualityResult
        )
        if (!prResult.success) {
            println("PR creation failed: ${prResult.errorMessage}")
            return@runBlocking PipelineResult(success = false, errorMessage = prResult.errorMessage)
        }
        println("PR created successfully")
        
        println("=== Pipeline Completed Successfully ===")
        return@runBlocking PipelineResult(success = true)
    }
}

data class PipelineResult(
    val success: Boolean,
    val errorMessage: String? = null
)
