package com.designtocode.domain.adapter

import com.designtocode.domain.model.QualityGateResult
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import kotlin.test.assertFalse
import kotlin.test.assertNotNull
import kotlin.test.assertTrue
import java.io.File

class GitHubCliAdapterTest {

    @TempDir
    lateinit var tempDir: File

    @Test
    fun shouldHandleGitErrorsGracefully() {
        // Given
        val gitHubCliAdapter = GitHubCliAdapter(tempDir)
        val invalidBranchName = "" // Invalid empty branch name

        // When
        val result = gitHubCliAdapter.createFeatureBranch(invalidBranchName)

        // Then
        assertFalse(result.success, "Should fail with invalid branch name")
        assertNotNull(result.errorMessage, "Error message should be present")
    }

    @Test
    fun shouldValidateBranchNamingConvention() {
        // Given
        val gitHubCliAdapter = GitHubCliAdapter(tempDir)
        val validBranchName = "feature/ai-gen-abc123"
        val invalidBranchName = "invalid-branch"

        // When
        val validResult = gitHubCliAdapter.createFeatureBranch(validBranchName)
        val invalidResult = gitHubCliAdapter.createFeatureBranch(invalidBranchName)

        // Then
        // Valid branch name should pass validation (may fail on git execution)
        assertTrue(validResult.errorMessage?.contains("Invalid branch name") != true,
            "Valid branch name should not be rejected by validation")

        // Invalid branch name should fail validation
        assertFalse(invalidResult.success, "Invalid branch name should be rejected")
        assertTrue(invalidResult.errorMessage?.contains("Invalid branch name") == true,
            "Should reject invalid branch name")
    }

    @Test
    fun shouldValidateCommitMessageFormat() {
        // Given
        val gitHubCliAdapter = GitHubCliAdapter(tempDir)
        val validMessage = "feat: add AI-generated code"
        val invalidMessage = "invalid message without type"

        // When
        val validResult = gitHubCliAdapter.commitChanges(validMessage)
        val invalidResult = gitHubCliAdapter.commitChanges(invalidMessage)

        // Then
        // Valid message should pass validation (may fail on git execution)
        assertTrue(validResult.errorMessage?.contains("Invalid commit message") != true,
            "Valid commit message should not be rejected by validation")

        // Invalid message should fail validation
        assertFalse(invalidResult.success, "Invalid commit message should be rejected")
        assertTrue(invalidResult.errorMessage?.contains("Invalid commit message") == true,
            "Should reject invalid commit message")
    }

    @Test
    fun shouldHandleEmptyCommitMessage() {
        // Given
        val gitHubCliAdapter = GitHubCliAdapter(tempDir)
        val emptyMessage = ""

        // When
        val result = gitHubCliAdapter.commitChanges(emptyMessage)

        // Then
        assertFalse(result.success, "Empty commit message should be rejected")
        assertTrue(result.errorMessage?.contains("cannot be empty") == true,
            "Should reject empty commit message")
    }

    @Test
    fun shouldHandleEmptyTitleInPRCreation() {
        // Given
        val gitHubCliAdapter = GitHubCliAdapter(tempDir)
        val title = ""
        val description = "Generated by AI pipeline"
        val qualityResult = QualityGateResult(
            passed = true,
            buildSuccess = true,
            coveragePercentage = 95.0
        )

        // When
        val result = gitHubCliAdapter.createPullRequest(title, description, qualityResult)

        // Then
        assertFalse(result.success, "Empty title should be rejected")
    }

    @Test
    fun shouldHandleBranchNameWithInvalidFormat() {
        // Given
        val gitHubCliAdapter = GitHubCliAdapter(tempDir)
        val invalidBranchName = "invalid-branch-format"

        // When
        val result = gitHubCliAdapter.createFeatureBranch(invalidBranchName)

        // Then
        assertFalse(result.success, "Invalid branch format should be rejected")
        assertTrue(result.errorMessage?.contains("Invalid branch name") == true)
    }

    @Test
    fun shouldHandleBranchNameWithoutFeaturePrefix() {
        // Given
        val gitHubCliAdapter = GitHubCliAdapter(tempDir)
        val invalidBranchName = "main-branch"

        // When
        val result = gitHubCliAdapter.createFeatureBranch(invalidBranchName)

        // Then
        assertFalse(result.success, "Branch without <prefix>/ shape should be rejected")
    }

    @Test
    fun shouldHandleCommitMessageWithoutType() {
        // Given
        val gitHubCliAdapter = GitHubCliAdapter(tempDir)
        val invalidMessage = "just a description without type"

        // When
        val result = gitHubCliAdapter.commitChanges(invalidMessage)

        // Then
        assertFalse(result.success, "Commit without type should be rejected")
        assertTrue(result.errorMessage?.contains("Invalid commit message") == true)
    }

    @Test
    fun shouldHandleCommitMessageWithInvalidType() {
        // Given
        val gitHubCliAdapter = GitHubCliAdapter(tempDir)
        val invalidMessage = "invalidtype: some description"

        // When
        val result = gitHubCliAdapter.commitChanges(invalidMessage)

        // Then
        assertFalse(result.success, "Commit with invalid type should be rejected")
    }

    @Test
    fun shouldHandleBranchNameTooShort() {
        // Given
        val gitHubCliAdapter = GitHubCliAdapter(tempDir)
        val shortBranchName = "f/ab"

        // When
        val result = gitHubCliAdapter.createFeatureBranch(shortBranchName)

        // Then
        assertFalse(result.success, "Too-short branch name should be rejected")
        assertNotNull(result.errorMessage)
    }
}
