package com.designToCode.infra.adapter

import com.designToCode.domain.port.GitOperationsPort
import com.designToCode.domain.port.PullRequest
import java.io.File

class GitHubCliAdapter(
    private val workspace: File
) : GitOperationsPort {

    override fun createBranch(branchName: String) {
        val process = ProcessBuilder("git", "checkout", "-b", branchName)
            .directory(workspace)
            .redirectErrorStream(true)
            .start()

        val exitCode = process.waitFor()
        
        if (exitCode != 0) {
            val output = process.inputStream.bufferedReader().readText()
            throw RuntimeException("Failed to create branch $branchName: $output")
        }
    }

    override fun commitChanges(message: String) {
        // Stage all changes
        val addProcess = ProcessBuilder("git", "add", ".")
            .directory(workspace)
            .redirectErrorStream(true)
            .start()
        addProcess.waitFor()

        // Commit
        val commitProcess = ProcessBuilder("git", "commit", "-m", message)
            .directory(workspace)
            .redirectErrorStream(true)
            .start()

        val exitCode = commitProcess.waitFor()
        
        if (exitCode != 0) {
            val output = commitProcess.inputStream.bufferedReader().readText()
            throw RuntimeException("Failed to commit changes: $output")
        }
    }

    override fun createPullRequest(
        sourceBranch: String,
        targetBranch: String,
        title: String,
        body: String
    ): PullRequest {
        val process = ProcessBuilder(
            "gh", "pr", "create",
            "--base", targetBranch,
            "--head", sourceBranch,
            "--title", title,
            "--body", body
        )
            .directory(workspace)
            .redirectErrorStream(true)
            .start()

        val exitCode = process.waitFor()
        
        if (exitCode != 0) {
            val output = process.inputStream.bufferedReader().readText()
            throw RuntimeException("Failed to create pull request: $output")
        }

        return PullRequest(
            sourceBranch = sourceBranch,
            targetBranch = targetBranch,
            title = title,
            body = body
        )
    }

    override fun getCurrentBranch(): String {
        val process = ProcessBuilder("git", "rev-parse", "--abbrev-ref", "HEAD")
            .directory(workspace)
            .redirectErrorStream(true)
            .start()

        val exitCode = process.waitFor()
        
        if (exitCode != 0) {
            val output = process.inputStream.bufferedReader().readText()
            throw RuntimeException("Failed to get current branch: $output")
        }

        return process.inputStream.bufferedReader().readText().trim()
    }

    fun generateBranchName(commitSha: String): String {
        return "feature/ai-gen-$commitSha"
    }

    fun buildValidationSummary(
        compilationSuccess: Boolean,
        lintSuccess: Boolean,
        testsPassed: Boolean,
        coveragePercentage: Int
    ): String {
        return """
            ## Automated Implementation Report
            This Pull Request was automatically generated by the Design-to-Code AI Pipeline.
            
            ### Validation Summary:
            - **Kotlin Code Generation:** Clean / Hexagonal Architecture standard.
            - **Tests:** JUnit 5 integration tests executed with Testcontainers.
            - **Quality Gate:** ${coveragePercentage}% Code Coverage verified by Kover/JaCoCo.
            - **Compilation:** ${if (compilationSuccess) "✅ Passed" else "❌ Failed"}
            - **Linting:** ${if (lintSuccess) "✅ Passed" else "❌ Failed"}
            - **Tests:** ${if (testsPassed) "✅ Passed" else "❌ Failed"}
            
            _Please review the generated implementation, architecture boundaries, and edge cases._
        """.trimIndent()
    }
}
